### ISSUE TITLE
crystalize method changes scope of module methods.

### ISSUE THREAD

**Issue by seandunn** [wouterken/crystalruby#3]
- ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]
- Crystal 1.12.0 (2024-04-09)

I'm not sure if this is an "issue" as such but I noticed something from the Readme quick start example:

```ruby
module Adder
  crystalize [a: :int, b: :int] => :int
  def add(a, b)
    a + b
  end
end

puts Adder.add(1, 2)
```

The crystalize method seems to be changing the scope of the `add` method to make it "class" level on `Adder`.

If you comment out `crystalize [a: :int, b: :int] => :int` so that the code runs as ruby ,you get `undefined method 'add' for module Adder (NoMethodError)`

Changing the method to `def self.add` and it works as expected with or without the crystalize call.

BTW: I just wanted to say how interesting and exciting this project is, thank you!

**Comment by wouterken** [comment]
Hey @seandunn 

Yes, I agree that at first glance it might seem counter-intuitive to see an instance method, begin to appear at the module level after crystalization.

Because the library relies heavily on FFI, it currently mimics the behaviour of FFI's `attach_function` and attaches at both the instance and the module level (see [here](https://github.com/ffi/ffi/blob/4b928c7e7eb9415f3827ff7a8c7a7fc8293a363f/lib/ffi/variadic.rb#L53)). This is also equivalent to the behaviour of `module_function` in Ruby (where any instance methods that have been declared module functions are also available at both the module and instance level)

Like yourself, I'm not sure if this is a problem or actually a convenience that is not without precedent.

I expect to evolve the behaviour once the library begins to offer a solution for stateful instance methods.

> Changing the method to def self.add and it works as expected with or without the crystalize call.

I should mention that at this stage, the method is no longer `crystalized` (the crystalization process currently hooks into `method_added`) so while it appears to be working as expected, that's down to it being pure Ruby!

**Comment by seandunn** [comment]
Aha!  That makes perfect sense, thanks Wouter.  My expectation on how I'd use the gem would be to start with ruby code then crystalize methods one by one.  So I don't see this would cause any issues with compatibility.

Thanks for the illuminating explanation.
